site_name: DJUTILS
site_url: https://djutils.org/
site_favicon: images/favicon.png
copyright: (c) 2015-2022 Delft University of Technology

theme: readthedocs

markdown_extensions:
  - admonition
  
extra_css:
  - custom.css
    
nav:
  - Home: index.md
  - DJUNITS: 
      - Introduction: djutils/index.md
      - DecoderDumper: djutils/decoder-dumper.md
      - Immutable Collections: djutils/immutable-collections.md
      - Event package: djutils/event.md
      - Complex numbers: djutils/complex-numbers.md
      - Complex math: djutils/complex-math.md
      - Logging helper classes: djutils/logging.md
      - Exception helper classes: djutils/exceptions.md
      - URLResource class: djutils/urlresource.md
      - Reflection helper classes: djutils/reflection.md
      - Means package: djutils/means.md
      - Metadata: djutils/metadata.md 
      - DJUTILS documentation: https://djutils.org/docs/current/djutils/index.html
      - DJUTILS API: https://djuils.org/docs/current/apidocs/djutils/index.html
  - DJUNITS-CLI:
      - Introduction: djutils-cli/index.html
      - DJUTILS-CLI usage: djutils-cli/usage.html
      - DJUTILS-CLI documentation: https://djutils.org/docs/current/djutils-cli/index.html
      - DJUTILS-CLI API: https://djuils.org/docs/current/apidocs/djutils-cli/index.html
  - DJUTILS documentation: https://djutils.org/docs/current/index.html
  - DJUTILS API: https://djuils.org/docs/current/apidocs/index.html
